name: yolo_trap_app
description: "Trap Application"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  #flutter_blue_plus: ^1.35.5
  cupertino_icons: ^1.0.8
  logger: ^2.5.0
  fixnum: ^1.1.1
  protobuf: ^4.1.0
  intl: ^0.20.2
  rxdart: ^0.28.0
  flex_color_scheme: ^8.2.0
  #webview_flutter:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  pigeon: ^25.5.0

flutter:
  uses-material-design: true

